POST http://fauques.freeboxos.fr:3000/matches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI0MjRiYjU2Yi00Y2E1LTRkZTYtYWU2Ni02NzQ0MGIzNTk4OTgiLCJ1c2VybmFtZSI6ImpvdWV1cjEiLCJpYXQiOjE2NDE1NTg4MTAsImV4cCI6MTY3MzExNjQxMH0.0R7rkQ8vjveJ3ptGzq5rQGBnmWOdFwUPVikVnC4kopY